# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [2]:
import numpy as np

In [2]:
# Exercise 1
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [5]:
# Exercise 2
zeros_array = np.zeros((3, 3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [10]:
# Exercise 3
nj=np.linspace(0,5,10)
nj

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])


---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [8]:
# Exercise 4
matrix=np.eye(5,5)
matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])


---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [18]:
# Exercise 5
random_matrix = np.random.rand(4, 4)
print(random_matrix)

[[0.48584978 0.59268173 0.18346799 0.28490454]
 [0.1884651  0.83672139 0.25971076 0.41326795]
 [0.3977896  0.21439634 0.05946878 0.88471468]
 [0.01575452 0.82352451 0.00981402 0.33090292]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [19]:
# Exercise 6
shape_of=np.shape(random_matrix)
shape_of

(4, 4)


---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [23]:
# Exercise 7
grid=np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])


---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [26]:
# Exercise 8
type(grid)

numpy.ndarray


---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [44]:
# Exercise 9
array = np.arange(1, 101)
even_numbers = array[array % 2 == 0]

print(even_numbers)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [53]:
# Exercise 10
random_matrix = np.random.randint(10, 51, size=(6, 6))
print(random_matrix)

[[31 35 23 24 36 21]
 [25 13 13 45 19 13]
 [16 29 35 43 24 27]
 [27 17 40 45 34 20]
 [41 43 35 44 21 42]
 [15 48 29 30 35 30]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [52]:
# Exercise 11
_arr=[[1,2,3,4,3,5,4,7]]
_arr[0][4:]

[3, 5, 4, 7]


---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [54]:
# Exercise 12
array = np.array([[1, 2, 3],
                  [4, 5, 6]])
total = array.sum()
print(total)

21



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [55]:
# Exercise 13
cal_arr=np.array([1,2,5,6,7,9])
mean=np.mean(cal_arr)
median=np.median(cal_arr)
standard_deviation=np.std(cal_arr)
print("Mean: ",mean)
print("Median: ",median)
print("Standard deviation: ",standard_deviation)

Mean:  5.0
Median:  5.5
Standard deviation:  2.7688746209726918



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [3]:
# Exercise 14
_array = np.array([5, 10, 3, 8, 2])
max_val = np.max(_array)
min_val = np.min(_array)

print("Maximum:", max_val)
print("Minimum:", min_val)

Maximum: 10
Minimum: 2



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [4]:
# Exercise 15
arr_ = np.random.randint(1, 100, size=20)
max_index = np.argmax(arr_ )

print("Array:", arr_ )
print("Index of Max Value:", max_index)

Array: [15 85 68 87 81 55 18 40 63 19 96 91 32 96 75 44 19 27 20 43]
Index of Max Value: 10



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [ ]:
# Exercise 16
array = np.array([1, 2, 3, 4, 5])
reversed_array = array[::-1]

reversed_array = array[::-1]

print("Reversed Array:", reversed_array)


---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [5]:
# Exercise 17
a = np.random.randint(1, 10, (3, 3))
b = np.random.randint(1, 10, (3, 3))
result = a * b

print("Matrix A:\n", a)
print("Matrix B:\n", b)
print("Element-wise Multiplication:\n", result)

Matrix A:
 [[8 8 8]
 [6 2 1]
 [8 5 4]]
Matrix B:
 [[8 6 2]
 [7 8 5]
 [5 6 9]]
Element-wise Multiplication:
 [[64 48 16]
 [42 16  5]
 [40 30 36]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [6]:
# Exercise 
array = np.array([1, 2, 3, 4])
diagonal_matrix = np.diag(array)

print("Diagonal Matix:\n", diagonal_matrix)

Diagonal Matix:
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [ ]:
# Exercise 19
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)

print("Matrix Multiplication:\n", result)


---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [7]:
# Exercise 20
matrix = np.array([[1, 2], [3, 4]])
flatened = matrix.flatten()
print("Flatened Array:", flatened)

Flatened Array: [1 2 3 4]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [9]:
# Exercise 21
a21 = np.array([[1, 2], [3, 4]])
b21 = np.array([[5, 6], [7, 8]])
vert_stack = np.vstack((a21, b21))
vert_stack

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])


---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [10]:
# Exercise 22
hori_stack = np.hstack((a21, b21))
hori_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])


---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [11]:
# Exercise 23
array23 = np.arange(10)
split_array = np.array_split(array23, 3)
split_array

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [12]:
# Exercise 24
random_array24 = np.random.rand(3, 3)
rounded_array = np.round(random_array24, 2)
rounded_array

array([[0.06, 0.75, 0.67],
       [0.59, 0.19, 0.12],
       [0.65, 0.3 , 0.25]])


---

### Exercise 25:
Find the unique elements of a NumPy array.


In [ ]:
# Exercise 25
array25 = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(array25)
unique_elements


---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [ ]:
# Exercise 26
array26 = np.array([2, 5, 3, 8, 1])
array26[array26 < 4] = 4



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [13]:
# Exercise 27
array_27 = np.array([1, 2, 3, 4])
cumulative_sum = np.cumsum(array_27)
cumulative_sum

array([ 1,  3,  6, 10])


---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [14]:
# Exercise 28
array28 = np.array([0, 1, 2, 0, 4])
nonzero_count = np.count_nonzero(array28)
nonzero_count 

3


---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [ ]:
# Exercise 29
array29 = np.random.randint(1, 100, 10)
sorted_array = np.sort(array29)


---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [15]:
# Exercise 30
matrix30 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 1]])
row_sum = matrix30.sum(axis=1)
col_sum = matrix30.sum(axis=0)
print('row-wise',row_sum)
print('column-wise',col_sum)

row-wise [ 6 15 16]
column-wise [12 15 10]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [16]:
# Exercise 31
array31 = np.random.rand(3, 3)
normalized_array = (array31 - np.min(array31)) / (np.max(array31) - np.min(array31))
normalized_array

array([[0.28025463, 0.28777434, 0.68793716],
       [0.        , 1.        , 0.86344731],
       [0.24018044, 0.01081017, 0.77297608]])


---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [ ]:
# Exercise 32
a32 = np.array([1, 2])
b32 = np.array([3, 4])
dot_product = np.dot(a32, b32)
dot_product


---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [17]:
# Exercise 33
matrix33 = np.array([[1, 2], [3, 4]])
trace_value = np.trace(matrix33)
trace_value

5


---

### Exercise 34:
Create a 2D array and swap two rows.


In [18]:
# Exercise 34
matrix34 = np.array([[1, 2], [3, 4], [5, 6]])
matrix34[[0, 2]] = matrix34[[2, 0]]
matrix34

array([[5, 6],
       [3, 4],
       [1, 2]])


---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [ ]:
# Exercise 35
array35 = np.array([1, 2, 3, 4])
column_vector = array35.reshape(-1, 1)
column_vector


---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [ ]:
# Exercise 36
matrix36 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
determinant = np.linalg.det(matrix36)


---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [19]:
# Exercise 37
matrix37 = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix37)
eigenvalues, eigenvectors

(array([2., 3.]),
 array([[1., 0.],
        [0., 1.]]))


---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [ ]:
# Exercise 38
A38 = np.array([[2, 3], [3, 4]])
b38 = np.array([8, 11])
solution = np.linalg.solve(A38, b38)
solution


---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [20]:
# Exercise 39
array39 = np.array([1, 2, 3, 4, 5])
noise = np.random.normal(0, 0.1, array39.shape)
noisy_array = array39 + noise
noisy_array

array([1.03783772, 2.06458776, 3.03502347, 4.04174483, 5.25241761])


---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [ ]:
# Exercise 40
matrix40 = np.random.randint(1, 10, (4, 4))
diagonal_elements = np.diag(matrix40)


---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [ ]:
# Exercise 41
array41 = np.random.randint(0, 100, 100)
clipped_array = np.clip(array41, 10, 50)
print("Exercise 41:", clipped_array)


---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [ ]:
# Exercise 42
rray42 = np.random.randn(3, 3)
array42[array42 < 0] = 0
print("Exercise 42:", array42)


---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [ ]:
# Exercise 43
a43 = np.array([1, 2, 3])
b43 = np.array([4, 5, 6])
inner = np.inner(a43, b43)
outer = np.outer(a43, b43)
print("Exercise 43 - Inner:", inner)
print("Exercise 43 - Outer:\n", outer)


---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [ ]:
# Exercise 44
points44 = np.random.rand(4, 2)
pairwise_distances = squareform(pdist(points44))
print("Exercise 44:\n", pairwise_distances)


---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [ ]:
# Exercise 45
dtype45 = [('name', 'U10'), ('age', 'i4'), ('height', 'f4')]
data45 = np.array([('Alice', 25, 5.5), ('Bob', 30, 6.1)], dtype=dtype45)
print("Exercise 45:\n", data45)


---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [ ]:
# Exercise 46
matrix46 = np.random.randint(0, 10, (5, 5))
unique_vals, counts = np.unique(matrix46, return_counts=True)
print("Exercise 46 - Matrix:\n", matrix46)
print("Unique values:", unique_vals)
print("Counts:", counts)


---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [ ]:
# Exercise 47
matrix47 = np.random.rand(3, 3)
row_mean = matrix47.mean(axis=1, keepdims=True)
normalized_rows = matrix47 - row_mean
print("Exercise 47:\n", normalized_rows)


---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [ ]:
# Exercise 48
array48 = np.random.randint(0, 100, 10)
any_above_50 = np.any(array48 > 50)
print("Exercise 48 - Array:", array48)
print("Any above 50?", any_above_50)


---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [ ]:
# Exercise 49
array49 = np.arange(10)
window_size = 3
moving_avg = np.convolve(array49, np.ones(window_size)/window_size, mode='valid')
print("Exercise 49 - Moving average:", moving_avg)


---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [ ]:
# Exercise 50
x50 = np.random.rand(10)
y50 = np.random.rand(10)
correlation_matrix = np.corrcoef(x50, y50)
print("Exercise 50 - Pearson correlation:\n", correlation_matrix)


---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [ ]:
# Exercise 51
radians = np.array([0, np.pi/4, np.pi/2, np.pi])
degrees = np.degrees(radians)
print(degrees)


---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [ ]:
# Exercise 52
_arr = np.random.rand(10)
variance = np.var(_arr)
std_dev = np.std(_arr)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [ ]:
# Exercise 53
array_2d = np.array([[10, 20, 5], [7, 8, 25]])
max_indices_axis0 = np.argmax(array_2d, axis=0)
max_indices_axis1 = np.argmax(array_2d, axis=1)
print("Max indices along axis 0:", max_indices_axis0)
print("Max indices along axis 1:", max_indices_axis1)


---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [ ]:
# Exercise 54
matrix = np.array([[4, 7], [2, 6]])
inverse = np.linalg.inv(matrix)
print("Inverse matrix:\n", inverse)


---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [ ]:
# Exercise 55
arr = np.random.rand(10)
standardized = (arr - np.mean(arr)) / np.std(arr)
print("Standardized array:", standardized)


---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [ ]:
# Exercise 56
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
add = a + b
subtract = a - b
print("Addition:", add)
print("Subtraction:", subtract)


---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [ ]:
# Exercise 57
arr = np.random.rand(10)
max_index = np.argmax(arr)
print("Array:", arr)
print("Index of max element:", max_index)


---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [ ]:
# Exercise 58
array_3x3 = np.array([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])
rotated = np.rot90(array_3x3)
print("Rotated array:\n", rotated)


---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [ ]:
# Exercise 59
matrix = np.array([[1, 2], [3, 4]])
fro_norm = np.linalg.norm(matrix, 'fro')
print("Frobenius norm:", fro_norm)


---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [ ]:
# Exercise 60
array_3d = np.random.randint(1, 10, (3, 3, 3))
subarray = array_3d[1:, :2, :2]
print("Original 3D array:\n", array_3d)
print("Sliced subarray:\n", subarray)


---